// SPDX-License-Identifier: Apache-2.0
//
// binding.ts — query→range binding persistence (Lane G).
//
// Persists SavedQuery records to a single Office document-settings key
// ("scx.queries") holding a JSON array.  The bearer token is NEVER stored here
// — only the endpoint host (no token, no full URI) per DECISIONS #6.
//
// All serialisation goes through the injected SettingsBackend so the module is
// fully testable without an Office host (inject memorySettingsBackend()).

import {
  type SettingsBackend,
  officeDocumentSettingsBackend,
} from "../connection/connectionStore.js";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

/**
 * Everything needed to re-run and rewrite a query result.
 *
 * DECISIONS #6 invariant: `endpointHost` is the bare host (e.g. "localhost" or
 * "spark.example.com") — NOT a full URI, NOT the bearer token. The token lives
 * in OfficeRuntime.storage (Lane I) and is fetched at refresh time.
 */
export interface SavedQuery {
  /** Stable unique identifier, generated by `newQueryId()`. */
  queryId: string;
  /** The SQL string to re-execute on refresh. */
  sql: string;
  /** Row cap passed to `bridge.runSQL`. */
  rowCap: number;
  /** Sheet the result was written to. */
  sheetName: string;
  /** Top-left cell address of the result range (e.g. "A1"). */
  anchorAddress: string;
  /**
   * Host component of the Spark Connect endpoint (no scheme, no port, no token).
   * Used to reconstruct the connection URI; the port + TLS flag live in
   * ConnectionConfig (Lane I), not here.
   */
  endpointHost: string;
  /** ISO-8601 creation timestamp (UTC). */
  createdAt: string;
}

// ---------------------------------------------------------------------------
// Internal constants
// ---------------------------------------------------------------------------

/** The single document-settings key that stores all SavedQuery records. */
const QUERIES_KEY = "scx.queries";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Load the raw SavedQuery array from the backend.
 * Returns an empty array when nothing has been saved yet or the stored value
 * is corrupt (fail-safe: a parse error means we start fresh).
 */
function loadRaw(backend: SettingsBackend): SavedQuery[] {
  const raw = backend.get(QUERIES_KEY);
  if (raw == null) return [];
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (!Array.isArray(parsed)) return [];
    // Keep only entries that look like SavedQuery (defensive — the array could
    // be from an older version or corrupted).
    return parsed.filter(isSavedQuery);
  } catch {
    return [];
  }
}

/**
 * Persist the raw SavedQuery array to the backend.
 */
async function saveRaw(queries: SavedQuery[], backend: SettingsBackend): Promise<void> {
  await backend.set(QUERIES_KEY, JSON.stringify(queries));
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Generate a new, unique query ID.
 *
 * Format: "q_" + millisecond timestamp + "_" + 6 random hex digits.
 * Collision probability under normal usage (< 1000 queries/second) is
 * negligible; uniqueness is verified in unit tests.
 */
export function newQueryId(): string {
  const ts = Date.now().toString(36);
  const rand = Math.floor(Math.random() * 0xffffff)
    .toString(16)
    .padStart(6, "0");
  return `q_${ts}_${rand}`;
}

/**
 * Persist a SavedQuery.  If a query with the same `queryId` already exists it
 * is replaced in-place (upsert); otherwise the record is appended.
 *
 * @param q       The query record to save.
 * @param backend Settings backend (default: Office document settings).
 */
export async function saveQueryBinding(
  q: SavedQuery,
  backend: SettingsBackend = officeDocumentSettingsBackend(),
): Promise<void> {
  const existing = loadRaw(backend);
  const idx = existing.findIndex((r) => r.queryId === q.queryId);
  if (idx >= 0) {
    existing[idx] = q;
  } else {
    existing.push(q);
  }
  await saveRaw(existing, backend);
}

/**
 * Load all persisted SavedQuery records.
 *
 * Returns an empty array when nothing has been saved yet or on parse failure
 * (fail-safe — the caller should not throw on a fresh workbook).
 *
 * Intentionally synchronous so callers can call it without awaiting a
 * settings-read round-trip; the backend's `get` is a synchronous cache read
 * (Office keeps an in-memory settings copy).
 *
 * @param backend Settings backend (default: Office document settings).
 */
export function loadQueryBindings(
  backend: SettingsBackend = officeDocumentSettingsBackend(),
): SavedQuery[] {
  return loadRaw(backend);
}

/**
 * Remove the SavedQuery with the given `queryId`.
 * No-op (and no error) if the ID is not found.
 *
 * @param queryId The ID of the query to remove.
 * @param backend Settings backend (default: Office document settings).
 */
export async function deleteQueryBinding(
  queryId: string,
  backend: SettingsBackend = officeDocumentSettingsBackend(),
): Promise<void> {
  const existing = loadRaw(backend);
  const filtered = existing.filter((r) => r.queryId !== queryId);
  // Only write back if something actually changed to avoid an unnecessary
  // saveAsync round-trip.
  if (filtered.length !== existing.length) {
    await saveRaw(filtered, backend);
  }
}

// ---------------------------------------------------------------------------
// Internal type guard
// ---------------------------------------------------------------------------

function isSavedQuery(v: unknown): v is SavedQuery {
  if (v == null || typeof v !== "object") return false;
  const o = v as Record<string, unknown>;
  return (
    typeof o["queryId"] === "string" &&
    typeof o["sql"] === "string" &&
    typeof o["rowCap"] === "number" &&
    typeof o["sheetName"] === "string" &&
    typeof o["anchorAddress"] === "string" &&
    typeof o["endpointHost"] === "string" &&
    typeof o["createdAt"] === "string"
  );
}
